version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.env:/app/.env
    command: npx nodemon --exec ts-node src/server.ts --watch src --ext ts

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  admin:
    build:
      context: ./admin
    container_name: admin
    ports:
      - "5174:5174"
    volumes:
      - ./admin:/app
      - /app/node_modules
    command: npm run dev -- --host --port 5174